Navy_System/config/routes.rb
NavySystem::Application.routes.draw do
# get "user_session/get_users"
  match 'login' => 'user_session#login', :as => :login
  match 'logout' => 'user_session#logout', :as => :logout
  match 'get_users' => 'user_session#get_users', :as => :get_users


  

  
  
  match 'qowa/vacations/getUserVacations' => 'qowa/vacations#getUserVacations', :as => :getUserVacations
  match 'qowa/vacations/user_vacations' => 'qowa/vacations#user_vacations', :as => :user_vacations  
  match 'qowa/vacations/user_vacations_brief' => 'qowa/vacations#user_vacations_brief', :as => :user_vacations_brief
  match 'qowa/users' => 'qowa/vacations#users', :as => :users

  namespace :qowa do
    resources :vacations
    resources :vacation_types
  end
  



  resources :user_session

  namespace :mostkhdmeen do
    resources :users
    resources :groups
  end

  

  root :to =>'user_session#login'

  match ':controller(/:action(/:id))(.:format)'

end

Navy_System/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id,:address, :blood, :group_id, :job_type, :military_number, :name, :near_relative, :note, :password, :password_confirmation, :phone, :rank_id, :start_date, :status, :tag_date, :tas_date, :type
  
  
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

  belongs_to :rank
  belongs_to :group

  has_many :vacations
  has_many :vacation_types, :through => :vacations
end

Navy_System/app/controllers/mostkhdmeen/users_controller.rb
class Mostkhdmeen::UsersController < ApplicationController
  # GET /mostkhdmeen/users
  # GET /mostkhdmeen/users.json
  def index
    @mostkhdmeen_users = User.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mostkhdmeen_users }
    end
  end

  # GET /mostkhdmeen/users/1
  # GET /mostkhdmeen/users/1.json
  def show
    @mostkhdmeen_user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mostkhdmeen_user }
    end
  end

  # GET /mostkhdmeen/users/new
  # GET /mostkhdmeen/users/new.json
  def new
    
    @mostkhdmeen_user = User.new 
    @groups = Group.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mostkhdmeen_user }
    end
  end

  # GET /mostkhdmeen/users/1/edit
  def edit
    @groups = Group.all
    @mostkhdmeen_user = User.find(params[:id])
    @edit_flag = true
  end

  # POST /mostkhdmeen/users
  # POST /mostkhdmeen/users.json
  def create
    @mostkhdmeen_user = User.new(params[:user])

    respond_to do |format|
      if @mostkhdmeen_user.save
        format.html { redirect_to mostkhdmeen_users_path, notice: 'User was successfully created.' }
        format.json { render json: @mostkhdmeen_user, status: :created, location: @mostkhdmeen_user }
      else
        format.html { render action: "new" }
        format.json { render json: @mostkhdmeen_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mostkhdmeen/users/1
  # PUT /mostkhdmeen/users/1.json
  def update
    @mostkhdmeen_user = User.find(params[:id])

    respond_to do |format|
      if @mostkhdmeen_user.update_attributes(params[:user])
        format.html { redirect_to mostkhdmeen_users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mostkhdmeen_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mostkhdmeen/users/1
  # DELETE /mostkhdmeen/users/1.json
  def destroy
    @mostkhdmeen_user = User.find(params[:id])
    @mostkhdmeen_user.destroy

    respond_to do |format|
      format.html { redirect_to mostkhdmeen_users_url }
      format.json { head :no_content }
    end
  end
  
  
 
  
end

Navy_System/app/helpers/mostkhdmeen/users_helper.rb
module Mostkhdmeen::UsersHelper
end

Navy_System/app/views/users/_form.html.erb
<%= form_for(@user, :html=>{:style=>"margin-right:400px;margin-top:50px; width:400px;", :class=>"well" } ) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    	<%= f.label "اسم المستخدم" %>
    	<%= f.text_field :name, :class=>"user_form_field" %>
  	</div>
  	
  	  <div class="field">
    	<%= f.label "الرقم العسكرى" %>
    	<%= f.text_field :military_number, :class=>"user_form_field" %>
  	</div>
  
  <div class="field">
    <%= f.label "كلمة المرور" %>
    <%= f.password_field :password, :class=>"user_form_field" %>
  </div>
  
  <div class="field">
    <%= f.label "تأكيد كلمة المرور" %>
    <%= f.password_field :password_confirmation, :class=>"user_form_field" %>
  </div>

	<div class="field">
	<%= f.label "رقم التلفون" %>
	<%= f.text_field :phone, :class=>"user_form_field" %>
  </div>
  
<div class="field">
	<%= f.label "ملاحظات" %>
	<%= f.text_field :note, :class=>"user_form_field" %>
  </div>
	
	
	

  
  
  
	
  <div class="field">
    <%= f.label "المجموعة" %>
	<%= f.select :group_id, options_from_collection_for_select(@groups, "id", "name"), :class=>"user_form_field", :prompt => '-- اختر مجموعة --',  %> 
  </div>
  
	 
  
  <div class="modal-footer" >
  <center>
    <%= f.submit "تسجيل المستخدم",:class=>"btn-large btn-primary" %>
  </center>
  </div>
<% end %>

Navy_System/app/views/users/index.html.erb
<ul class="nav nav-tabs" id="Menus" style = "margin-right:20px ;font: bold 1.20em Tahoma; sans-serif;">
	<li >
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق القوة وتمام الأفراد" >القـــوة</a>
	</li>
	<li class="active" >
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق تأمين الدخول علي منظومة ق.ق.ب و مراقبة سير العمل للمستخدمين">المستخدمين</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="قاعدة إدخال البيانات">إدخال البيانات</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title=" تطبيق بنك المعلومات">بنك المعلومات</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق أجازات القادة">اجازات القادة</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق الحافظة الآلية و متابعة التأشيرات و الإلتزمات الرئيسية للسيد قائد القوات البحرية/السيد رئيس الأركان">الحافظة</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق المكافآت و الحوافز">المكافآت و الحوافز</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق متابعة عضويات دور القوات البحرية" >عضويات</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق الأرشيف الإلكتروني لقيادة القوات البحرية" >الأرشيف</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق التصوير بالكمبيوتر" >التصوير</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق المتابعة الآلية لوحدات القوات البحرية" >المتابعة</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيقات دعم و إتخاذ القرار الإداري" >دعم وإتخاذ القرار</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="شاشات سير العمل اليومي" >سير العمل</a>
	</li>
</ul>

<div style="float:right;">
	<ul  style="font: normal 15px Tahoma; margin-top: 30px; margin-right: 25px;" id="sideMenus" class="nav nav-list bs-docs-sidenav affix" >
		<li >
			<a href=<%=new_group_path%> >تسجيل مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li >
			<a href=<%=groups_path%>>بيان بالمجموعات<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href=<%=new_user_path%>>تسجيل المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li class="active">
			<a href=<%=users_path%>>بيان بالمستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
	</ul>
</div>

<table style="width: 60%; height: 60%; float:left; margin-top: 30px;
margin-left: 130px;" class="table table-bordered">
	<tr>
		<th><center>اسم المستخدم</center></th>
		<th><center> الرقم العسكرى</center></th>
		<th><center> المجموعة </center></th>
		<th><center>تاريخ التجنيد  </center></th>
		<th><center>تاريخ الضم</th>
		<th><center>تاريخ التسليم</center></th>
		<th><center>ملاحظات</center></th>
		<th colspan='3'></th>
	</tr>

	<% @users.each do |user| %>
	<tr>
		<td><center><%= user.name %></center></td>
		<td><center><%= "#{user.military_number}" %></center></td>
		<td><center><%= Group.find_by_id(user.group).name %></td>
		<td><center><%= "#{user.tag_date}" %></center></td>
		<td><center><%= "#{user.start_date}" %></center></td>
		<td><center><%= "#{user.tas_date}" %></center></td>
		<td><center><%= "#{user.note}" %></center></td>
		
		<td><center><button class="btn btn-success"><%= link_to 'تعديل', edit_user_path(user) %></button></center></td>
		<td><center><button class="btn btn-danger"><%= link_to 'حذف', user, method: :delete, data: { confirm: 'حذف المستخدم ؟' } %></center></button></td>
	</tr>
	<% end %>
</table>



</div>

Navy_System/app/views/users/new.html.erb
<ul class="nav nav-tabs" id="Menus" style = "margin-right:20px ;font: bold 1.20em Tahoma; sans-serif;">
	<li >
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق القوة وتمام الأفراد" >القـــوة</a>
	</li>
	<li class="active" >
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق تأمين الدخول علي منظومة ق.ق.ب و مراقبة سير العمل للمستخدمين">المستخدمين</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="قاعدة إدخال البيانات">إدخال البيانات</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title=" تطبيق بنك المعلومات">بنك المعلومات</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق أجازات القادة">اجازات القادة</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق الحافظة الآلية و متابعة التأشيرات و الإلتزمات الرئيسية للسيد قائد القوات البحرية/السيد رئيس الأركان">الحافظة</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق المكافآت و الحوافز">المكافآت و الحوافز</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق متابعة عضويات دور القوات البحرية" >عضويات</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق الأرشيف الإلكتروني لقيادة القوات البحرية" >الأرشيف</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق التصوير بالكمبيوتر" >التصوير</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيق المتابعة الآلية لوحدات القوات البحرية" >المتابعة</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="تطبيقات دعم و إتخاذ القرار الإداري" >دعم وإتخاذ القرار</a>
	</li>
	<li>
		<a href="#" data-toggle="tooltip" data-placement="bottom" title="شاشات سير العمل اليومي" >سير العمل</a>
	</li>
</ul>

<div style="float:right;">
	<ul  style="font: normal 15px Tahoma; margin-top: 30px; margin-right: 25px;" id="sideMenus" class="nav nav-list bs-docs-sidenav affix" >
		<li >
			<a href=<%=new_group_path%> >تسجيل مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li >
			<a href=<%=groups_path%>>بيان بالمجموعات<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li class="active">
			<a href=<%=new_user_path%>>تسجيل المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href=<%=users_path%>>بيان بالمستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
	</ul>
</div>



<%= render 'form' %>