Navy_System/config/routes.rb
NavySystem::Application.routes.draw do
# get "user_session/get_users"
  match 'login' => 'user_session#login', :as => :login
  match 'logout' => 'user_session#logout', :as => :logout
  match 'get_users' => 'user_session#get_users', :as => :get_users


  

  
  
  match 'qowa/vacations/getUserVacations' => 'qowa/vacations#getUserVacations', :as => :getUserVacations
  match 'qowa/vacations/user_vacations' => 'qowa/vacations#user_vacations', :as => :user_vacations  
  match 'qowa/vacations/user_vacations_brief' => 'qowa/vacations#user_vacations_brief', :as => :user_vacations_brief
  match 'qowa/users' => 'qowa/vacations#users', :as => :users

  namespace :qowa do
    resources :vacations
    resources :vacation_types
  end
  



  resources :user_session

  namespace :mostkhdmeen do
    resources :users
    resources :groups
  end

  

  root :to =>'user_session#login'

  match ':controller(/:action(/:id))(.:format)'

end

Navy_System/app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :id, :name, :note, :open_all

  has_many :users
end

Navy_System/app/controllers/mostkhdmeen/groups_controller.rb
class Mostkhdmeen::GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @edit_flag = true
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to mostkhdmeen_groups_path, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to mostkhdmeen_groups_path, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to mostkhdmeen_groups_url }
      format.json { head :no_content }
    end
  end
end

Navy_System/app/controllers/mostkhdmeen/users_controller.rb
class Mostkhdmeen::UsersController < ApplicationController
  # GET /mostkhdmeen/users
  # GET /mostkhdmeen/users.json
  def index
    @mostkhdmeen_users = User.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mostkhdmeen_users }
    end
  end

  # GET /mostkhdmeen/users/1
  # GET /mostkhdmeen/users/1.json
  def show
    @mostkhdmeen_user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mostkhdmeen_user }
    end
  end

  # GET /mostkhdmeen/users/new
  # GET /mostkhdmeen/users/new.json
  def new
    
    @mostkhdmeen_user = User.new 
    @groups = Group.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mostkhdmeen_user }
    end
  end

  # GET /mostkhdmeen/users/1/edit
  def edit
    @groups = Group.all
    @mostkhdmeen_user = User.find(params[:id])
    @edit_flag = true
  end

  # POST /mostkhdmeen/users
  # POST /mostkhdmeen/users.json
  def create
    @mostkhdmeen_user = User.new(params[:user])

    respond_to do |format|
      if @mostkhdmeen_user.save
        format.html { redirect_to mostkhdmeen_users_path, notice: 'User was successfully created.' }
        format.json { render json: @mostkhdmeen_user, status: :created, location: @mostkhdmeen_user }
      else
        format.html { render action: "new" }
        format.json { render json: @mostkhdmeen_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mostkhdmeen/users/1
  # PUT /mostkhdmeen/users/1.json
  def update
    @mostkhdmeen_user = User.find(params[:id])

    respond_to do |format|
      if @mostkhdmeen_user.update_attributes(params[:user])
        format.html { redirect_to mostkhdmeen_users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mostkhdmeen_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mostkhdmeen/users/1
  # DELETE /mostkhdmeen/users/1.json
  def destroy
    @mostkhdmeen_user = User.find(params[:id])
    @mostkhdmeen_user.destroy

    respond_to do |format|
      format.html { redirect_to mostkhdmeen_users_url }
      format.json { head :no_content }
    end
  end
  
  
 
  
end

Navy_System/app/helpers/mostkhdmeen/groups_helper.rb
module Mostkhdmeen::GroupsHelper
end

Navy_System/app/helpers/mostkhdmeen/users_helper.rb
module Mostkhdmeen::UsersHelper
end

Navy_System/app/views/mostkhdmeen/groups/_form.html.erb
<%= form_for([:mostkhdmeen, @group], :html=>{:style=>"margin-right:400px;margin-top:50px; width:400px;", :class=>"well" }) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "اسم المجموعة" %>
    <%= f.text_field :name %>
  </div>
  
  <div class="field" >
    <%= f.label "ملاحظات" %>
    <%= f.text_field :note %>
  </div>
  
  <div class="field">
    <%= f.label "فتح جميع التطبيقات" %>
    <%= f.check_box :open_all %>
  </div>
  
  <div class="modal-footer">
  	<center>
  	<%= f.submit @edit_flag?"حفظ":"تسجيل المجموعة" , :class=>"btn-large btn-primary"  %>	
    </center>
  </div>
<% end %>

Navy_System/app/views/mostkhdmeen/groups/edit.html.erb
<div class="well" style="margin:20px">
	<div style="float:right; margin-top: -10px;">
		<h4>تـــــــعديل مجموعـــــات المستــــخدمين</h4تسجيل></h4>
	</div>
	
</div>

<div style="float:right;">
	<ul  style="font: normal 15px Tahoma; margin-top: 30px; margin-right: 25px;" id="sideMenus" class="nav nav-list bs-docs-sidenav affix" >
		<li >
			<a href=<%=new_mostkhdmeen_group_path%> >تسجيل مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li class="active">
			<a href=<%=mostkhdmeen_groups_path%>>بيان بالمجموعات<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href=<%=new_mostkhdmeen_user_path%>>تسجيل المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href=<%=mostkhdmeen_users_path%>>بيان بالمستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
	</ul>
</div>

<%= render 'form' %>

Navy_System/app/views/mostkhdmeen/groups/index.html.erb
<div class="well" style="margin:20px">
	<div style="float:right; margin-top: -10px;">
		<h4>بيـــــــــان بمجموعـــــات المستخـــــدمين</h4>
	</div>
	
</div>


<div style="float:right;">
	<ul  style="font: normal 15px Tahoma; margin-top: 30px; margin-right: 25px;" id="sideMenus" class="nav nav-list bs-docs-sidenav affix" >
		<li >
			<a href=<%=new_mostkhdmeen_group_path%> >تسجيل مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li class="active">
			<a href=<%=mostkhdmeen_groups_path%>>بيان بالمجموعات<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href=<%=new_mostkhdmeen_user_path%>>تسجيل المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href=<%=mostkhdmeen_users_path%>>بيان بالمستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
	</ul>
</div>

<table style="width: 60%; height: 60%; float:left; margin-top: 30px;
margin-left: 130px;" class="table table-bordered">
	<tr>
		<th><center>اسم المجموعة</center></th>
		<th><center>الكود</center></th>
		<th><center>عدد اﻷفراد</center></th>
		<th><center>ملاحظات</center></th>
		<th><center>فتح جميع التطبيقات</center></th>
		<th colspan='2'></th>
	</tr>

	<% @groups.each do |group| %>
	<tr>
		<td><center><%= group.name %></center></td>
		<td><center><%= group.id %></center></td>
		<td><center><%= group.users.count %></center></td>
		<td><center><%= "#{group.note}" %></center></td>
		<td><center>
		 <%if group.open_all%>
		 	نعم
		 <%else%>
		 ---
		 <%end%>
		 </center></td>
		
		<td><center><button class="btn btn-success"><%= link_to 'تعديل', edit_mostkhdmeen_group_path(group) %></button></center></td>
		<td><center><button class="btn btn-danger"><%= link_to 'حذف', mostkhdmeen_group_path(group), method: :delete, data: { confirm: 'حذف المجموعة ؟' } %></center></button></td>
	</tr>
	<% end %>
</table>



</div>

Navy_System/app/views/mostkhdmeen/groups/new.html.erb
<div class="well" style="margin:20px">
	<div style="float:right; margin-top: -10px;">
		<h4>تســــــجيل مجــموعـــات المستخدميـــن</h4تسجيل></h4>
	</div>
	
</div>

<div style="float:right;">
	<ul  style="font: normal 15px Tahoma; margin-top: 30px; margin-right: 25px;" id="sideMenus" class="nav nav-list bs-docs-sidenav affix" >
		<li class="active">
			<a href=<%=new_mostkhdmeen_group_path%> >تسجيل مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li >
			<a href=<%=mostkhdmeen_groups_path%>>بيان بالمجموعات<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص مجموعات المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href=<%=new_mostkhdmeen_user_path%>>تسجيل المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href=<%=mostkhdmeen_users_path%>>بيان بالمستخدمين<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">خصائص المستخدمين<i class="icon-chevron-left"></i></a>
		</li>
	</ul>
</div>



<%= render 'form' %>

Navy_System/app/views/mostkhdmeen/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Goup:</b>
  <%= @group.id %>
</p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @group.note %>
</p>

<p>
  <b>Open all:</b>
  <%= @group.open_all %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>