Navy_System/config/routes.rb
NavySystem::Application.routes.draw do
# get "user_session/get_users"
  match 'login' => 'user_session#login', :as => :login
  match 'logout' => 'user_session#logout', :as => :logout
  match 'get_users' => 'user_session#get_users', :as => :get_users


  

  
  
  match 'qowa/vacations/getUserVacations' => 'qowa/vacations#getUserVacations', :as => :getUserVacations
  match 'qowa/vacations/user_vacations' => 'qowa/vacations#user_vacations', :as => :user_vacations  
  match 'qowa/vacations/user_vacations_brief' => 'qowa/vacations#user_vacations_brief', :as => :user_vacations_brief
  match 'qowa/users' => 'qowa/vacations#users', :as => :users

  namespace :qowa do
    resources :vacations
    resources :vacation_types
  end
  



  resources :user_session

  namespace :mostkhdmeen do
    resources :users
    resources :groups
  end

  

  root :to =>'user_session#login'

  match ':controller(/:action(/:id))(.:format)'

end

Navy_System/app/models/qowa.rb
module Qowa
  def self.table_name_prefix
    'qowa_'
  end
end

Navy_System/app/controllers/qowa/vacation_types_controller.rb
class Qowa::VacationTypesController < ApplicationController
  # GET /qowa/vacation_types
  # GET /qowa/vacation_types.json
  def index
    @qowa_vacation_types = VacationType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qowa_vacation_types }
    end
  end

  # GET /qowa/vacation_types/1
  # GET /qowa/vacation_types/1.json
  def show
    @qowa_vacation_type = VacationType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qowa_vacation_type }
    end
  end

  # GET /qowa/vacation_types/new
  # GET /qowa/vacation_types/new.json
  def new
    @qowa_vacation_type = VacationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qowa_vacation_type }
    end
  end

  # GET /qowa/vacation_types/1/edit
  def edit
    @edit_flag = true
    @qowa_vacation_type = VacationType.find(params[:id])
  end

  # POST /qowa/vacation_types
  # POST /qowa/vacation_types.json
  def create
    @qowa_vacation_type = VacationType.new(params[:vacation_type])

    respond_to do |format|
      if @qowa_vacation_type.save
        format.html { redirect_to qowa_vacation_types_path, notice: 'Vacation type was successfully created.' }
        format.json { render json: @qowa_vacation_type, status: :created, location: @qowa_vacation_type }
      else
        format.html { render action: "new" }
        format.json { render json: @qowa_vacation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qowa/vacation_types/1
  # PUT /qowa/vacation_types/1.json
  def update
    @qowa_vacation_type = VacationType.find(params[:id])

    respond_to do |format|
      if @qowa_vacation_type.update_attributes(params[:vacation_type])
        format.html { redirect_to qowa_vacation_types_path, notice: 'Vacation type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qowa_vacation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qowa/vacation_types/1
  # DELETE /qowa/vacation_types/1.json
  def destroy
    @qowa_vacation_type = VacationType.find(params[:id])
    @qowa_vacation_type.destroy

    respond_to do |format|
      format.html { redirect_to qowa_vacation_types_url }
      format.json { head :no_content }
    end
  end
end

Navy_System/app/controllers/qowa/vacations_controller.rb
class Qowa::VacationsController < ApplicationController
  # GET /qowa/vacations
  # GET /qowa/vacations.json
  def index
    if(params[:to_date])
      @qowa_vacations = Vacation.where("to_date >= ?", params[:to_date])
    else
      date = Date.today
      @qowa_vacations = Vacation.where("to_date >= ?", date)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qowa_vacations }
    end
  end
  
  def user_vacations
      @qowa_vacations = Vacation.where("user_id = ?", params[:user_id])
  end
  
  
  def user_vacations_brief
    @brief = []
    users = User.all
    types = VacationType.all
    
    
    i = 0
    users.each do |user|
      j = 0
      @brief[i] = []
      @brief[i][j] = user.id
      j = j + 1
      @brief[i][j] = user.name
      j = j + 1
        
      types.each do |type|
        
        @brief[i][j] = type.name
        j = j + 1
                   
        vacations = Vacation.where("user_id=? AND vacation_type_id = ?", user.id, type.id)
        numDays = 0
        vacations.each do |vac|
          numDays = vac.duration + numDays
        end 
        
        @brief[i][j] = numDays
        j = j + 1
      end 
    end
    i = i + 1
  end

  # GET /qowa/vacations/1
  # GET /qowa/vacations/1.json
  def show
    @qowa_vacation = Vacation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qowa_vacation }
    end
  end

  # GET /qowa/vacations/new
  # GET /qowa/vacations/new.json
  def new
    @create_flag = true
    @qowa_vacation = Vacation.new
    @groups=  Group.all
    @users = []
    @vacation_types = VacationType.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qowa_vacation }
    end
  end

  # GET /qowa/vacations/1/edit
  def edit
    @create_flag = false
    @qowa_vacation = Vacation.find(params[:id])
    @groups = Group.all
    @vacation_types = VacationType.all
  end

  # POST /qowa/vacations
  # POST /qowa/vacations.json
  def create
    p "========================================================"
    p params[:vacation]
    p "========================================================"
    
    to = Date.parse(params[:vacation][:to_date])
    from = Date.parse(params[:vacation][:from_date])
    params[:vacation][:duration] = (to- from).to_i
    @qowa_vacation = Vacation.new(params[:vacation])

    respond_to do |format|
      if @qowa_vacation.save
        p @qowa_vacation.to_date

        format.html { redirect_to qowa_vacations_path, notice: 'Vacation was successfully created.' }
        format.json { render json: @qowa_vacation, status: :created, location: @qowa_vacation }
      else
        format.html { render action: "new" }
        format.json { render json: @qowa_vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qowa/vacations/1
  # PUT /qowa/vacations/1.json
  def update
    @qowa_vacation = Vacation.find(params[:id])
    to = Date.parse(params[:vacation][:to_date])
    from = Date.parse(params[:vacation][:from_date])
    params[:vacation][:duration] = (to- from).to_i
    respond_to do |format|
      if @qowa_vacation.update_attributes(params[:vacation])
        format.html { redirect_to qowa_vacations_path, notice: 'Vacation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qowa_vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qowa/vacations/1
  # DELETE /qowa/vacations/1.json
  def destroy
    @qowa_vacation = Vacation.find(params[:id])
    @qowa_vacation.destroy

    respond_to do |format|
      format.html { redirect_to qowa_vacations_url }
      format.json { head :no_content }
    end
  end

  def getKhwareg
    dd    respond_to do |format|
      format.html
      format.json { render json: @qowa_vacations }
    end
  end

  def getUserVacations
    @qowa_vacations = Vacation.where("user_id = ? AND from_date = ? AND to_date = ?", params[:user_id], params[:from_date], params[:to_date])
    respond_to do |format|
      format.html
      format.json { render json: @qowa_vacations }
    end
  end
  
  
   def users
    @mostkhdmeen_users = User.all
    
  end

end

Navy_System/app/helpers/qowa/vacation_types_helper.rb
module Qowa::VacationTypesHelper
end

Navy_System/app/helpers/qowa/vacations_helper.rb
module Qowa::VacationsHelper
end

Navy_System/app/views/qowa/vacation_types/_form.html.erb
<%= form_for([:qowa, @qowa_vacation_type], :html=>{:style=>"margin-right:400px;margin-top:50px; width:400px;", :class=>"well" }) do |f| %>
  <% if @qowa_vacation_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qowa_vacation_type.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @qowa_vacation_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "نــــــــوع الأجــــازة" %>
    <%= f.text_field :name %>
  </div>
  
 
  
  <div class="modal-footer">
  	<center>
    <%= f.submit @edit_flag?"حفظ":"تسجيل اﻷجازة" , :class=>"btn-large btn-primary"  %>
    </center>
  </div>
<% end %>

Navy_System/app/views/qowa/vacation_types/edit.html.erb
<%= render 'form' %>

Navy_System/app/views/qowa/vacation_types/index.html.erb
<div class="well" style="margin:20px">
	<div style="float:right; margin-top: -10px;">
		<h4>تســـــــجيل أنواع الأجازات</h4>
	</div>

	<button class="btn btn-info" style="margin-right:50px">
		<i class=" icon-add  icon-white"></i><%= link_to 'تسجيل نوع جديد', new_qowa_vacation_type_path %>
	</button></center></td>

</div>

<div style="float:right;">
	<ul  style="font: normal 15px Tahoma; margin-top: 30px; margin-right: 25px;" id="sideMenus" class="nav nav-list bs-docs-sidenav affix" >
		<li class="active">
			<a href=<%= qowa_vacation_types_path%> >تسجيل أنواع الأجازات<i class="icon-chevron-left"></i></a>
		</li>

		<li>
			<a href="<%= new_qowa_vacation_path%>">تسجيل أجازات اﻷفراد<i class="icon-chevron-left"></i></a>
		</li>

		<li>
			<a href=<%= qowa_vacations_path%>>بيان بالخوارج<i class="icon-chevron-left"></i></a>
		</li>

		<li>
			<a href="#">بيان أجازات اﻷفراد<i class="icon-chevron-left"></i></a>
		</li>

		<li>
			<a href="/qowa/users">بيانات طاقم فرع السكرتارية<i class="icon-chevron-left"></i></a>
		</li>
	</ul>
</div>

<table  style="margin-top:30px; margin-left:80px; width:70%; float: left " class="table table-bordered">
	<tr >
		<th width="30%" ><h4>
		<center>
			الكود
		</center></h4></th>
		<th  width="40%" ><h4>
		<center>
			نوع الأجازة
		</center></h4></th>
		<th width="30%" colspan="2"></th>

	</tr>

	<% @qowa_vacation_types.each do |agaza|%>
	<tr >
		<td><h5>
		<center>
			<%= agaza.id%>
		</center></h5></td>
		<td><h5>
		<center>
			<%= agaza.name%>
		</center></h5></td>
		<td><h5>
		<center>
			<button class="btn btn-info">
				<i class=" icon-pencil  icon-white"></i><%= link_to 'تعديــل', edit_qowa_vacation_type_path(agaza) %>
			</button>
		</center></h5></td>
		<td><h5>
		<center>
			<button class="btn btn-danger">
				<i class=" icon-trash  icon-white"></i><%= link_to 'حذف', qowa_vacation_type_path(agaza), method: :delete, data: { confirm: 'حــذف ؟' } %>
			</button>
		</center></h5></td>
	</tr>
	<%end%>

</table>

</div>

<script>
	$(document).ready(function() {

		$("#Menus > li > a").tooltip();

		$('li').click(function() {
			//select tthe active element in the current list by $("#idOfTheList > .active")
			$("#" + this.parentElement.getAttribute("id") + " > .active").removeClass("active")
			this.setAttribute("class", "active")
		});

		$('#Menus').tab('show');

		$('.carousel').carousel({
			interval : 4000
		});

	});

</script>

Navy_System/app/views/qowa/vacation_types/new.html.erb
<div class="well" style="margin:20px">
	<div style="float:right; margin-top: -10px;">
		<h4>تســــــــجيل نوع أجازة جديد</h4>
	</div>
	
</div>



<div style="float:right;">
	<ul  style="font: normal 15px Tahoma; margin-top: 30px; margin-right: 25px;" id="sideMenus" class="nav nav-list bs-docs-sidenav affix" >
		<li class="active">
			<a href=<%=qowa_vacation_types_path%> >تسجيل أنواع الأجازات<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="<%=new_qowa_vacation_path%>">تسجيل أجازات اﻷفراد<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href=<%=qowa_vacations_path%>>بيان بالخوارج<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="#">بيان أجازات اﻷفراد<i class="icon-chevron-left"></i></a>
		</li>
		
		<li>
			<a href="/qowa/users" >بيانات طاقم فرع السكرتارية<i class="icon-chevron-left"></i></a>
		</li>
	</ul>
</div>


<%= render 'form' %>

Navy_System/app/views/qowa/vacation_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @qowa_vacation_type.name %>
</p>


<%= link_to 'Edit', edit_qowa_vacation_type_path(@qowa_vacation_type) %> |
<%= link_to 'Back', qowa_vacation_types_path %>